	graph TD;
		A[Study Design] --> B[CRFs and eDTs];
		B --> C[SDTM Define-XML];
		C --> D[aCRFs];
		D --> E[Shell Datasets];
		E --> F[Populate CRFs];
		F --> G[ODS];
		G --> H[oak.sdtm Algorithms];
		H --> I[SDTM Datasets];
		I --> J[Open Rule Set];
		J --> K[Conformance Report];